version: 2
updates:
- package-ecosystem: pip
  directory: "/device"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 20
  reviewers:
  - nakafuji-m
  - tak-st
  - akisu1016
  - toyoda9
  assignees:
  - nakafuji-m
  - akisu1016
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.3.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  rebase-strategy: disabled
